
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Javier
 */
public class Consulta1 extends javax.swing.JFrame {

    private String columnas[] = {"Nombre", "apellido"};
    private String filas[][];
    
    private static Consulta1 instance = null;
    
    private DefaultTableModel tabla;
    private DefaultTableModel tabla2;
    
    /**
     * Creates new form Consulta1
     */
    public Consulta1() {
        initComponents();
        instance = this;
        tabla = new DefaultTableModel(filas, columnas);
        jTable1.setModel(tabla);
        
        tabla2 = new DefaultTableModel(filas, columnas);
        jTable2.setModel(tabla2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Producto mas caro:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static void init(){
        initTheme();
        setBootstrap();
        instance = new Consulta1();
        instance.setVisible(true);
        instance.setDefaultCloseOperation(Consulta1.DISPOSE_ON_CLOSE);
        
        instance.updateJTableWith(bs.model.getProductWithMaxValue());
        
        instance.updateJTable2With(bs.model.consulta1());
    }
    
    public static void initTheme() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
    
    public void getDataAndUpdate() {
        List<Map<String, String>> rows = bs.model.getProductWithMaxValue();
    }
    
    public void updateJTableWith(List<Map<String, String>> rows) {
        setBootstrap();
        System.out.println("Producto mas caro" + rows);
        updateTableModel(
            Utils.listOfListsToArrayFromMap(rows),
            getColumnsNamesFromList(rows)
        );
    }
    
    public void updateJTable2With(List<Map<String, String>> rows) {
        setBootstrap();
        System.out.println("Producto mas caro" + rows);
        updateTableModel2(
            Utils.listOfListsToArrayFromMap(rows),
            getColumnsNamesFromList(rows)
        );
    }
    
    public String[] getColumnsNamesFromList(List<Map<String, String>> rows) {
        String[] newColumns = new String[0];
        if (!rows.isEmpty()) {
            Map<String, String> row = rows.get(0);
            newColumns = new String[row.size()];
            int index = 0;
            for (Map.Entry e : row.entrySet()) {
                newColumns[index++] = e.getKey().toString();
            }
        }
        return newColumns;
    }
    
    public void updateJTableWith(String tableName) {
        setBootstrap();
        Map<String, List<String>> tableNames = bs.model.getTableNames();
        List<String> namesList = tableNames.get(tableName);
        System.out.println("Columnas de " + tableName + ": " + namesList);
        updateTableModel(Utils.listOfListsToArray(bs.model.selectAllFromLoader(tableName), tableName), 
                Utils.listToArray(namesList));
        System.out.println("Actualizacion Correcta con " + tableName);
    }
    
    public static Bootstrap bs = null;
    
    public static void setBootstrap(){
        if (bs == null){
            bs = Bootstrap.getInstance();
        }
    }
    
    private void updateTableModel(Object rows[][], String columns[]){
        tabla.setDataVector(rows, columns);
        tabla.fireTableDataChanged();
    }
    
    private void updateTableModel2(Object rows[][], String columns[]){
        tabla2.setDataVector(rows, new String[]{"etapa", "ci"});
        tabla2.fireTableDataChanged();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
