
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Victor
 */
public class adminPanel extends javax.swing.JPanel {

    private String columnas[] = {"Nombre", "apellido"};
    private String filas[][];
    
    private String columnas2[] = {"Nombre", "Fecha", "data"};
    DefaultTableModel tabla;
    String actualDBTable;    
    
    /**
     * Creates new form adminPanel
     */
    public adminPanel() {
        initComponents();
        tabla = new DefaultTableModel(filas, columnas);
        jTable1.setModel(tabla);
    }
    
    private void updateTableModel(Object rows[][], String columns[]){
        // tabla = new DefaultTableModel(rows, columns);
        
        tabla.setDataVector(rows, columns);
        tabla.fireTableDataChanged();
        
        // jTable2.setModel(tabla);
        // jScrollPane2.setViewportView(jTable2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(74, 28));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void updateJTableWith(String tableName) {
        setBootstrap();
        Map<String, List<String>> tableNames = bs.model.getTableNames();
        List<String> namesList = tableNames.get(tableName);
        System.out.println("Columnas de " + tableName + ": " + namesList);
        
        updateTableModel(Utils.listOfListsToArray(bs.model.selectAllFromLoader(tableName)), Utils.listToArray(namesList));
        
        System.out.println("Actualizacion Correcta con " + tableName);
    }
    
    public Bootstrap bs = null;
    
    public void setBootstrap(){
        if (bs == null){
            bs = Bootstrap.getInstance();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
